Repository BHoM/LadybugTools_Toolkit, pull requests merged in 2023-11, with the labels that each got.

#133 Added additional Pollination version check
  LadybugTools_Engine/Compute/InstallPythonEnv_LBT.cs
  LadybugTools_Engine/Query/IsPollinationInstalled.cs
Labels: severity:low, size:XS, type:feature

#135 Removed auto-constructors for finicky objects
  LadybugTools_Engine/Compute/EPWtoCSV.cs
  LadybugTools_Engine/Compute/ExternalComfort.cs
  LadybugTools_Engine/Compute/GEMtoHBJSON.cs
  LadybugTools_Engine/Compute/HBJSONtoGEM.cs
  LadybugTools_Engine/Compute/SimulationId.cs
  LadybugTools_Engine/Compute/SimulationResult.cs
  LadybugTools_Engine/Convert/ToShelter.cs
  LadybugTools_Engine/Create/AnalysisPeriod.cs
  LadybugTools_Engine/Create/EnergyMaterial.cs
  LadybugTools_Engine/Create/EnergyMaterialVegetation.cs
  LadybugTools_Engine/Create/Location.cs
  LadybugTools_Engine/Create/Shelter.cs
  LadybugTools_Engine/Create/Typology.cs
  LadybugTools_oM/AnalysisPeriod.cs
  LadybugTools_oM/EnergyMaterial.cs
  LadybugTools_oM/EnergyMaterialVegetation.cs
  LadybugTools_oM/ExternalComfort.cs
  LadybugTools_oM/LadybugTools_oM.csproj
  LadybugTools_oM/Location.cs
  LadybugTools_oM/Shelter.cs
  LadybugTools_oM/SimulationResult.cs
  LadybugTools_oM/Typology.cs
Labels: severity:low, size:S, type:feature

#138 Changed paths from C:/ProgramData to generic ProgramData folder
  LadybugTools_Engine/Compute/InstallPythonEnv_LBT.cs
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/bhom/__init__.py
  LadybugTools_Engine/Query/IsPollinationInstalled.cs
Labels: type:compliance

#141 Re-implemented GetMaterial and GetTypology methods
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/bhom/wrapped/get_typology.py
  LadybugTools_Engine/Query/GetMaterial.cs
  LadybugTools_Engine/Query/GetTypology.cs
  LadybugTools_Engine/Versioning_70.json
Labels: severity:low, size:S, type:feature, priority:low

#145 Fix for EPWToCSV
  LadybugTools_Engine/Compute/EPWtoCSV.cs
Labels: type:bug

#149 Adapter Serialisation: DataType now serialises properly
  LadybugTools_Adapter/Convert/FromBHoM.cs
  LadybugTools_Adapter/Convert/MetaData/DataType.cs
  LadybugTools_Adapter/Convert/ToBHoM.cs
  LadybugTools_oM/Collections/EPW.cs
Labels: type:bug

#148 Added 'source' to Wind objects
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/helpers.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/wind.py
  LadybugTools_Engine/Python/tests/test_wind.py
Labels: type:feature

#151 Added version check to existing environment query
  LadybugTools_Engine/Compute/InstallPythonEnv_LBT.cs
  LadybugTools_Engine/LadybugTools_Engine.csproj
  LadybugTools_Engine/Query/IsPollinationInstalled.cs
  LadybugTools_oM/LadybugTools_oM.csproj
Labels: severity:medium, size:S, type:bug
