Repository BHoM/LadybugTools_Toolkit, pull requests merged in 2024-12, with the labels that each got.

#268 Move base plots to Python_Toolkit
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/bhom/wrapped/plot/diurnal.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/bhom/wrapped/plot/heatmap.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/categorical/categorical.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/external_comfort/_externalcomfortbase.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/helpers.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/plot/_diurnal.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/plot/_evaporative_cooling_potential.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/plot/_heatmap.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/plot/_misc.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/plot/_radiant_cooling_potential.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/plot/_timeseries.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/plot/_utci.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/plot/utilities.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/wind.py
  LadybugTools_Engine/Python/tests/test_plot.py
Labels: type:feature

#262 Added several plot methods and fixed a few minor bugs/warnings
  LadybugTools_Adapter/AdapterActions/Execute.cs
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/bhom/wrapped/plot/directional_solar_radiation.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/categorical/categorical.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/external_comfort/comfort_feasibility.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/external_comfort/utci.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/helpers.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/ladybug_extension/epw.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/plot/__utci_prototypes.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/plot/_evaporative_cooling_potential.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/plot/_misc.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/plot/_psychrometric.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/plot/_seasonality.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/plot/_utci.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/plot/colormaps.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/solar.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/wind.py
  LadybugTools_Engine/Python/tests/test_categorical.py
  LadybugTools_Engine/Python/tests/test_plot.py
  LadybugTools_Engine/Python/tests/test_solar.py
Labels: severity:low, size:S, type:bug, type:feature, priority:low

#278 Height above ground in the wind class now defaults to 10.0 meters
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/wind.py
Labels: type:bug

#279 Handle NoneType in plot_windmatrix to Prevent Errors
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/wind.py
Labels: good first issue, type:bug
