Repository BHoM/LadybugTools_Toolkit, pull requests merged in 2024-06, with the labels that each got.

#198 Updated nuspec to include python code files
  .ci/BHoMBot/Nuget/BHoM.Interop.LadybugTools.nuspec
Labels: type:compliance

#199 Updated displayed framework and version for python in nuspec
  .ci/BHoMBot/Nuget/BHoM.Interop.LadybugTools.nuspec
Labels: type:compliance

#203 Cast radiation_porosity and wind_porosity to list(float)
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/external_comfort/_shelterbase.py
Labels: type:bug

#205 Fixed bhom_analytics logger
  .ci/BHoMBot/Nuget/BHoM.Interop.LadybugTools.nuspec
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/bhom/__init__.py
Labels: type:bug

#209 Fixed deprecation warnings for python unit tests
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/external_comfort/shelter.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/ladybug_extension/datacollection.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/ladybug_extension/epw.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/plot/_diurnal.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/plot/_misc.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/plot/_sunpath.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/solar.py
  LadybugTools_Engine/Python/tests/test_helpers.py
  LadybugTools_Engine/Python/tests/test_ladybug_extension/test_datacollection.py
  LadybugTools_Engine/Python/tests/test_plot.py
Labels: type:compliance

#214 Fixed python Materials enum invalid keys
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/external_comfort/material.py
Labels: type:bug

#215 Update AssemblyFileVersion to 7.3
  LadybugTools_Adapter/LadybugTools_Adapter.csproj
  LadybugTools_Engine/LadybugTools_Engine.csproj
  LadybugTools_oM/LadybugTools_oM.csproj
Labels: type:compliance

#216 Features for various wind methods
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/helpers.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/wind.py
Labels: type:feature
