Repository BHoM/LadybugTools_Toolkit, pull requests merged in 2025-01, with the labels that each got.

#274 Add console logger for this toolkit
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/__init__.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/bhom/__init__.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/bhom/logging.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/external_comfort/_externalcomfortbase.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/external_comfort/_simulatebase.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/external_comfort/spatial/compare.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/external_comfort/spatial/spatial_comfort.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/helpers.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/honeybee_extension/simulation/radiance.py
Labels: type:external-api-changes

#283 Re-add solar radiation plot to adapter actions
  LadybugTools_Adapter/AdapterActions/Execute.cs
  LadybugTools_Adapter/Convert/MetaData/PlotInformation.cs
  LadybugTools_Adapter/LadybugTools_Adapter.csproj
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/bhom/wrapped/metadata/solar_radiation_metadata.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/bhom/wrapped/plot/directional_solar_radiation.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/solar.py
  LadybugTools_oM/ExecuteCommands/SolarRadiationPlotCommand.cs
  LadybugTools_oM/MetaData/SolarRadiationData.cs
  LadybugTools_oM/Versioning81.json
Labels: type:feature

#284 Correct file name for versioning file
  LadybugTools_oM/Versioning81.json
  LadybugTools_oM/Versioning_81.json
Labels: type:bug

#287 Adapter: added check for environment existing, and separated out execute command methods
  LadybugTools_Adapter/AdapterActions/Execute.cs
  LadybugTools_Adapter/AdapterActions/Execute/DiurnalPlotCommand.cs
  LadybugTools_Adapter/AdapterActions/Execute/GetMaterialCommand.cs
  LadybugTools_Adapter/AdapterActions/Execute/GetTypologyCommand.cs
  LadybugTools_Adapter/AdapterActions/Execute/HeatPlotCommand.cs
  LadybugTools_Adapter/AdapterActions/Execute/RunExternalComfortCommand.cs
  LadybugTools_Adapter/AdapterActions/Execute/RunSimulationCommand.cs
  LadybugTools_Adapter/AdapterActions/Execute/SolarRadiationPlotCommand.cs
  LadybugTools_Adapter/AdapterActions/Execute/SunPathPlotCommand.cs
  LadybugTools_Adapter/AdapterActions/Execute/UTCIHeatPlotCommand.cs
  LadybugTools_Adapter/AdapterActions/Execute/WindroseCommand.cs
  LadybugTools_Adapter/LadybugTools_Adapter.cs
Labels: type:feature

#286 Walkability time calculations and walkability heatmap plot added inside externalcomfortbase
  LadybugTools_Engine/Python/src/data/walkability.csv
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/external_comfort/_externalcomfortbase.py
Labels: type:feature

#289 Fix warning when inputting a valid matplotlib colourmap to commands
  LadybugTools_Adapter/Convert/ToColourMap.cs
Labels: type:bug

#270 Added comfort feasibility methods
  LadybugTools_Engine/Python/requirements.txt
Labels: severity:low, size:S, type:feature, priority:low

#258 Added SRI estimation methods
  LadybugTools_Engine/Python/src/data/sri_data.csv
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/__init__.py
  LadybugTools_Engine/Python/src/ladybugtools_toolkit/honeybee_extension/sri.py
  LadybugTools_Engine/Python/tests/test_honeybee_extension/test_sri.py
Labels: good first issue, size:S, type:feature, priority:low
